credentials:
  usernames:
    medistream:
      name: Admin
      password: $2b$12$pyNFKdqyzaf1No8C6VIdmuhuuNE.GjP9xCv2Yz1t64K7AgFUaFTRy
# nlp2th
cookie:
  expiry_days: 30
  key: whisperandllm # Must be string
  name: treatment-summary